import type { AggregatedResult } from "../scoring/types.js";

export function generateLeaderboardMarkdown(
  results: AggregatedResult[],
  runner: string,
): string {
  const now = new Date().toISOString().split("T")[0];
  const rows = results.map((r) => {
    const passPercent = Math.round(r.passRate * 100);
    return `| ${r.configId} | ${passPercent}% | ${r.avgTokens.toLocaleString("en-US", { maximumFractionDigits: 0 })} | ${(r.avgTimeMs / 1000).toFixed(1)}s | $${r.avgCostUsd.toFixed(4)} | **${r.score}** |`;
  });

  return `# Leaderboard

> Auto-generated on ${now}. Runner: **${runner}**.

| Config | Pass Rate | Avg Tokens | Avg Time | Avg Cost | Score |
|--------|-----------|------------|----------|----------|-------|
${rows.join("\n")}

## Scoring

- Pass Rate: 40%
- Token Efficiency: 25%
- Time Efficiency: 20%
- Cost Efficiency: 15%

Best performer per metric gets 100, others scaled proportionally. Median of 3 runs per task.

---

*Generated by [Agent Config Arena](https://github.com/SingggggYee/agent-config-arena). Run \`node dist/index.js leaderboard\` to regenerate.*
`;
}
